### ISSUE TITLE
Support core protocols for deref and mutation

### ISSUE THREAD

**Issue by ranfdev** [squint-cljs/cherry#132]
I'm trying to write a wrapper around solid-js' signals, specifically I'm trying to add support for `@signal` and `(swap! signal ...)`.

The following code
```clojure
(ns test)

(deftype Signal []
  IDeref ;; even tried with cljs.core.IDeref and clojure.core.IDeref
  (-deref [this]
          2))

(prn @(Signal.))
```
returns the error

```
Error: No protocol method IDeref.-deref defined for type object: [object Object]
```

This solid-js wrapper would need support for IDeref, IReset and ISwap.
Custom Protocols are already supported, but these core ones are not.

**Comment by borkdude** [comment]
I pushed one part of the solution to main and this now works:

```
$ ./node_cli.js -e "(deftype Signal [] IDeref (-deref [this] 1)) (prn (deref (Signal.)))"
1
```

when running cherry in development mode with `bb dev`.

I still have to check whether this solution works when cherry is advanced compiled, I expect not, but I'll let you know.

**Comment by borkdude** [comment]
After adding an extern, it also worked with advanced mode:

```
$ ./node_cli.js --xshow -e "(deftype Signal [] IDeref (-deref [this] 1)) (prn (deref (Signal.)))"
1
```

**Comment by borkdude** [comment]
Feel free to follow up with more issues, after you have a change to test this. Can you test this locally perhaps? `bb build` is how you build the project.
