### ISSUE TITLE
UMD build stopped working

### ISSUE THREAD

**Issue by hatemhosny** [squint-cljs/cherry#135]
hi @borkdude 

I want to upgrade the cherry version supported on [LiveCodes](https://livecodes.io/?template=clojurescript).
I'm currently using the [umd build](https://github.com/squint-cljs/cherry/issues/101) of version 0.0.4

since version 0.1.6 the umd build gives an error like this:
`Uncaught TypeError: Cannot read properties of undefined (reading 'g')`
The code is minified with no source maps, so I cannot tell what is missing.

However, the esm build works fine.

This is a reproduction for the error:
https://livecodes.io/?x=id/g873swiuhkb

Thank you.

**Comment by borkdude** [comment]
Thanks for letting me know, I'll take a look tomorrow

**Comment by borkdude** [comment]
I published a new version in which this should be fixed.

**Comment by hatemhosny** [comment]
That now works very well.
https://livecodes.io/?x=id/utv2t5tjwr5

Thank you!
