### ISSUE TITLE
Async doesn't work with anonymous functions

### ISSUE THREAD

**Issue by jakub-stastny** [squint-cljs/cherry#142]
Unlike with `defn` and with instance methods on a class, anonymous functions defined with `(fn ^:async [])` loose the `async` when compiled.

Here's the [repro](https://gist.github.com/jakub-stastny/3331488f39e7586a4a77811ed4ee7752).

**Comment by jakub-stastny** [comment]
Actually this doesn't work even in BB/CLJ.

**ChatGPT:** _The reason you are getting nil when calling meta on a function defined using fn is because fn itself does not automatically store metadata on the function object. Metadata like ^:async applied directly to an anonymous function (fn) in this way is ignored._

_In Clojure, metadata can be attached to vars, not to anonymous functions directly created by fn. When using defn, you’re attaching metadata to the var associated with the function, not the function itself. fn, however, doesn’t create a var—it creates a raw function object._

That made me fix it in BB/CLJ:

```clojure
(prn (meta (fn ^:async [])))                    ; => nil
(prn (meta (with-meta (fn []) {:async true})))  ; => {:async true}
```

**However none of this actually fixed it in Cherry. So there goes my question, how do I use anonymous asynchronous functions? I need them in fn generators.**

**Comment by borkdude** [comment]
@jakub-stastny The supported way currently is to write:

```
^:async (fn []
          (js/console.log "HERE"))
```

but we could support it on the vector as well I guess

**Comment by borkdude** [comment]
or actually, the documented way in the README is this:

```
(^:async fn []
 (js/console.log "HERE"))
```

**Comment by borkdude** [comment]
The stuff on the vector is usually used for return values, so I think it already works like it should. It's similar to how `:once` metadata is used in Clojure:

https://ask.clojure.org/index.php/13050/what-does-once-meta-applied-for-anon-function-mean
