### ISSUE TITLE
= is throwing an "_EQ_ not defined"  error at runtime

### ISSUE THREAD

**Issue by alexdao3** [squint-cljs/cherry#79]
```
$ ./node_cli.js -e '(= 1 2)'
file:///Users/borkdude/dev/cherry/.tmpQ1aZ4r/cherry.mjs:1
_EQ_.call(null, 1, 2);
^
```

**Comment by borkdude** [comment]
This is an advanced compilation bug with shadow-cljs. cc @thheller

**Comment by borkdude** [comment]
In more detail:

Shadow-cljs optimizes symbol constants like this. If you have `'=` then shadow-cljs writes:

```
cljs$cst$_EQ_ = new Symbol(..., "=")
```

But when you write `'_EQ_` it also writes:

```
cljs$cst$_EQ_ = new Symbol(..., "_EQ_")
```

hence the conflict. In cherry we have both the `'=` and `'_EQ_` symbols as compile time constants.
